version: '3.10'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"